import { GameCatalogueItem } from '../../interfaces/Game';

export const mockGameListData: GameCatalogueItem[] = [
  {
    id: 'qt-0001',
    title: 'Forecast Talent',
    description: 'Inside from lately stress why lie here yet vanish in.',
    studio: 'Endorphina',
    rating: 1.3740153594669717,
    thumbnail: 'https://placehold.co/300x200?text=Forecast+Talent',
    type: 'roulette',
    categories: ['classic'],
    rtp: 94.82816456782004,
    volatility: 'high',
    release_date: '2022-11-16T20:24:40.893715587Z',
    features: ['gamble feature', 'cascading reels', 'bonus round', 'scatters'],
    has_jackpot: true,
    demo_url: 'https://demo.casino.com/game/forecast-talent-1',
    provider_game_id: 'forecast-talent-1',
    supported_platforms: ['tablet', 'mobile'],
  },
  {
    id: 'qt-0002',
    title: 'Encompassing Posse',
    description: 'Impromptu Swazi that where melt those in troop been time.',
    studio: 'Merkur',
    rating: 4,
    thumbnail: 'https://placehold.co/300x200?text=Encompassing+Posse',
    type: 'crash',
    categories: ['live', 'new'],
    rtp: 92.41532035736998,
    volatility: 'medium',
    release_date: '2025-04-03T06:25:22.148859612Z',
    features: ['scatters'],
    has_jackpot: false,
    demo_url: 'https://demo.casino.com/game/encompassing-posse-2',
    provider_game_id: 'encompassing-posse-2',
    supported_platforms: ['tablet'],
  },
  {
    id: 'qt-0003',
    title: 'Actuating Gang',
    description: 'Day well then so whom caravan whom as yourself yours.',
    studio: 'Push Gaming',
    rating: 1.3416742462323619,
    thumbnail: 'https://placehold.co/300x200?text=Actuating+Gang',
    type: 'roulette',
    categories: ['bonus buy', 'featured'],
    rtp: 94.90545331833387,
    volatility: 'high',
    release_date: '2017-07-12T03:42:03.897442669Z',
    features: ['cascading reels', 'free spins', 'autoplay'],
    has_jackpot: false,
    demo_url: 'https://demo.casino.com/game/actuating-gang-3',
    provider_game_id: 'actuating-gang-3',
    supported_platforms: ['mobile'],
  },
  {
    id: 'qt-0004',
    title: 'Switchable Sunshine',
    description:
      'A lake exaltation certain accordingly basket barely class on we.',
    studio: 'Betsoft',
    rating: 4,
    thumbnail: 'https://placehold.co/300x200?text=Switchable+Sunshine',
    type: 'baccarat',
    categories: ['bonus buy', 'new'],
    rtp: 94.56763159397276,
    volatility: 'medium',
    release_date: '2024-01-26T16:38:54.348276992Z',
    features: ['free spins'],
    has_jackpot: false,
    demo_url: 'https://demo.casino.com/game/switchable-sunshine-4',
    provider_game_id: 'switchable-sunshine-4',
    supported_platforms: ['desktop'],
  },
  {
    id: 'qt-0005',
    title: 'Horizontal Basket',
    description:
      'Constantly whichever Marxist this that does Caesarian he summation of.',
    studio: 'Pragmatic Play',
    rating: 4.821660537147224,
    thumbnail: 'https://placehold.co/300x200?text=Horizontal+Basket',
    type: 'slot',
    categories: ['featured'],
    rtp: 90.65193870822709,
    volatility: 'high',
    release_date: '2022-08-21T13:12:27.729042948Z',
    features: ['autoplay', 'multipliers', 'gamble feature'],
    has_jackpot: false,
    demo_url: 'https://demo.casino.com/game/horizontal-basket-5',
    provider_game_id: 'horizontal-basket-5',
    supported_platforms: ['mobile', 'desktop'],
  },
  {
    id: 'qt-0006',
    title: 'Attitude-Oriented Harvest',
    description:
      'Whose daily how sharply so yearly regiment nightly instead since.',
    studio: 'Booming Games',
    rating: 3,
    thumbnail: 'https://placehold.co/300x200?text=Attitude-Oriented+Harvest',
    type: 'slot',
    categories: ['megaways'],
    rtp: 95.31310816201972,
    volatility: 'medium',
    release_date: '2024-01-14T06:50:19.183939501Z',
    features: ['wilds', 'scatters'],
    has_jackpot: false,
    demo_url: 'https://demo.casino.com/game/attitude-oriented-harvest-6',
    provider_game_id: 'attitude-oriented-harvest-6',
    supported_platforms: ['mobile'],
  },
  {
    id: 'qt-0007',
    title: 'Object-Based Bread',
    description: 'My these peep closely wear one week some might on.',
    studio: 'Relax Gaming',
    rating: 5,
    thumbnail: 'https://placehold.co/300x200?text=Object-Based+Bread',
    type: 'slot',
    categories: ['classic', 'megaways'],
    rtp: 93.24188792059576,
    volatility: 'high',
    release_date: '2016-09-18T06:00:19.300494234Z',
    features: ['respins', 'gamble feature', 'scatters', 'bonus round'],
    has_jackpot: false,
    demo_url: 'https://demo.casino.com/game/object-based-bread-7',
    provider_game_id: 'object-based-bread-7',
    supported_platforms: ['desktop', 'tablet'],
  },
  {
    id: 'qt-0008',
    title: 'Cloned Ostrich',
    description:
      'Fondly board before daily those brace regiment meanwhile myself scale.',
    studio: 'Hacksaw Gaming',
    rating: 1,
    thumbnail: 'https://placehold.co/300x200?text=Cloned+Ostrich',
    type: 'crash',
    categories: ['bonus buy', 'new'],
    rtp: 88.84383703628579,
    volatility: 'high',
    release_date: '2023-10-09T19:52:15.504940604Z',
    features: ['wilds', 'autoplay', 'expanding symbols', 'bonus round'],
    has_jackpot: true,
    demo_url: 'https://demo.casino.com/game/cloned-ostrich-8',
    provider_game_id: 'cloned-ostrich-8',
    supported_platforms: ['mobile'],
  },
  {
    id: 'qt-0009',
    title: 'Implemented Mob',
    description:
      'Sheaf woman yesterday him then monthly besides be muster cousin.',
    studio: 'Merkur',
    rating: 2.996475213086761,
    thumbnail: 'https://placehold.co/300x200?text=Implemented+Mob',
    type: 'slot',
    categories: ['bonus buy', 'tournament'],
    rtp: 95.14192131150972,
    volatility: 'medium',
    release_date: '2022-08-14T03:46:10.333540736Z',
    features: ['expanding symbols'],
    has_jackpot: false,
    demo_url: 'https://demo.casino.com/game/implemented-mob-9',
    provider_game_id: 'implemented-mob-9',
    supported_platforms: ['desktop', 'mobile'],
  },
  {
    id: 'qt-0010',
    title: 'Parallelism Party',
    description: 'Later up bravo wake of college incredibly us mine wild.',
    studio: 'Relax Gaming',
    rating: 1.557163783885575,
    thumbnail: 'https://placehold.co/300x200?text=Parallelism+Party',
    type: 'blackjack',
    categories: ['featured', 'jackpot'],
    rtp: 96.49925886457747,
    volatility: 'low',
    release_date: '2025-04-23T08:06:20.501631735Z',
    features: ['scatters'],
    has_jackpot: false,
    demo_url: 'https://demo.casino.com/game/parallelism-party-10',
    provider_game_id: 'parallelism-party-10',
    supported_platforms: ['desktop', 'mobile'],
  },
  {
    id: 'qt-0011',
    title: 'Throughput Number',
    description: 'We fierce next patrol i.e. ouch nightly himself whose me.',
    studio: 'Spinomenal',
    rating: 1.9328301494063773,
    thumbnail: 'https://placehold.co/300x200?text=Throughput+Number',
    type: 'roulette',
    categories: ['featured', 'bonus buy', 'megaways'],
    rtp: 88.11436616439163,
    volatility: 'low',
    release_date: '2016-03-14T07:17:03.996652384Z',
    features: ['wilds', 'autoplay', 'respins'],
    has_jackpot: false,
    demo_url: 'https://demo.casino.com/game/throughput-number-11',
    provider_game_id: 'throughput-number-11',
    supported_platforms: ['mobile', 'desktop'],
  },
  {
    id: 'qt-0012',
    title: 'Profit-Focused Hatred',
    description:
      'Fortnightly whom stack dynasty whose troupe it library cautious instance.',
    studio: 'Gamomat',
    rating: 1.823842938720455,
    thumbnail: 'https://placehold.co/300x200?text=Profit-Focused+Hatred',
    type: 'roulette',
    categories: ['live', 'jackpot'],
    rtp: 89.2975372548649,
    volatility: 'low',
    release_date: '2024-03-17T05:51:18.198265688Z',
    features: ['autoplay', 'bonus round', 'cascading reels'],
    has_jackpot: false,
    demo_url: 'https://demo.casino.com/game/profit-focused-hatred-12',
    provider_game_id: 'profit-focused-hatred-12',
    supported_platforms: ['mobile'],
  },
  {
    id: 'qt-0013',
    title: 'Forecast Divorce',
    description: 'At because lucky am how none but of what beyond.',
    studio: 'Big Time Gaming',
    rating: 4.11655260914535,
    thumbnail: 'https://placehold.co/300x200?text=Forecast+Divorce',
    type: 'slot',
    categories: ['tournament', 'jackpot'],
    rtp: 96.36202431827114,
    volatility: 'high',
    release_date: '2025-06-17T22:22:08.342701315Z',
    features: ['expanding symbols', 'autoplay'],
    has_jackpot: false,
    demo_url: 'https://demo.casino.com/game/forecast-divorce-13',
    provider_game_id: 'forecast-divorce-13',
    supported_platforms: ['tablet'],
  },
  {
    id: 'qt-0014',
    title: 'Orchestration Nest',
    description: 'Caravan any none it our then over hedge that incredibly.',
    studio: 'ReelPlay',
    rating: 4.7988631149639716,
    thumbnail: 'https://placehold.co/300x200?text=Orchestration+Nest',
    type: 'roulette',
    categories: ['classic', 'new', 'jackpot'],
    rtp: 98.50135248672343,
    volatility: 'high',
    release_date: '2016-05-19T11:18:37.695468567Z',
    features: ['wilds', 'multipliers', 'respins', 'bonus round'],
    has_jackpot: false,
    demo_url: 'https://demo.casino.com/game/orchestration-nest-14',
    provider_game_id: 'orchestration-nest-14',
    supported_platforms: ['tablet'],
  },
  {
    id: 'qt-0015',
    title: 'Attitude Staff',
    description: 'Its earlier handle did ream them tomorrow is someone gently.',
    studio: 'Merkur',
    rating: 1,
    thumbnail: 'https://placehold.co/300x200?text=Attitude+Staff',
    type: 'slot',
    categories: ['tournament', 'jackpot'],
    rtp: 94.1380321440943,
    volatility: 'medium',
    release_date: '2018-07-26T06:08:05.635045193Z',
    features: ['free spins'],
    has_jackpot: false,
    demo_url: 'https://demo.casino.com/game/attitude-staff-15',
    provider_game_id: 'attitude-staff-15',
    supported_platforms: ['mobile', 'tablet'],
  },
  {
    id: 'qt-0016',
    title: 'Exuding Bundle',
    description: 'In lastly when lingering few well address which comb which.',
    studio: 'GameArt',
    rating: 1.6699008606991237,
    thumbnail: 'https://placehold.co/300x200?text=Exuding+Bundle',
    type: 'blackjack',
    categories: ['classic', 'bonus buy', 'featured'],
    rtp: 88.80978857331255,
    volatility: 'medium',
    release_date: '2023-03-19T22:45:03.791845071Z',
    features: ['bonus round', 'free spins', 'expanding symbols', 'autoplay'],
    has_jackpot: false,
    demo_url: 'https://demo.casino.com/game/exuding-bundle-16',
    provider_game_id: 'exuding-bundle-16',
    supported_platforms: ['desktop', 'mobile'],
  },
  {
    id: 'qt-0017',
    title: 'Client-Server Chair',
    description: 'March dynasty time hers above here over until openly climb.',
    studio: 'Thunderkick',
    rating: 3.5517037439816415,
    thumbnail: 'https://placehold.co/300x200?text=Client-Server+Chair',
    type: 'slot',
    categories: ['tournament', 'new'],
    rtp: 92.58373232543481,
    volatility: 'high',
    release_date: '2020-01-01T01:16:37.343771359Z',
    features: ['autoplay', 'respins', 'gamble feature', 'cascading reels'],
    has_jackpot: true,
    demo_url: 'https://demo.casino.com/game/client-server-chair-17',
    provider_game_id: 'client-server-chair-17',
    supported_platforms: ['desktop', 'tablet'],
  },
  {
    id: 'qt-0018',
    title: 'Matrices World',
    description: 'Here who hmm those above beautifully some am anyone troop.',
    studio: 'Tom Horn',
    rating: 4.963352365660979,
    thumbnail: 'https://placehold.co/300x200?text=Matrices+World',
    type: 'roulette',
    categories: ['classic', 'tournament'],
    rtp: 91.91293410549625,
    volatility: 'medium',
    release_date: '2024-04-11T09:34:57.529272883Z',
    features: ['scatters', 'multipliers', 'expanding symbols', 'wilds'],
    has_jackpot: false,
    demo_url: 'https://demo.casino.com/game/matrices-world-18',
    provider_game_id: 'matrices-world-18',
    supported_platforms: ['desktop'],
  },
  {
    id: 'qt-0019',
    title: 'Toolset Covey',
    description:
      'What prickling they growth dream outside back this greatly you.',
    studio: 'Endorphina',
    rating: 3.4271290684021745,
    thumbnail: 'https://placehold.co/300x200?text=Toolset+Covey',
    type: 'slot',
    categories: ['live', 'bonus buy', 'new'],
    rtp: 91.98963823332807,
    volatility: 'medium',
    release_date: '2020-09-25T01:15:21.143735803Z',
    features: ['bonus round', 'respins', 'gamble feature', 'free spins'],
    has_jackpot: false,
    demo_url: 'https://demo.casino.com/game/toolset-covey-19',
    provider_game_id: 'toolset-covey-19',
    supported_platforms: ['tablet'],
  },
  {
    id: 'qt-0020',
    title: 'High-Level Body',
    description:
      'Nest bale at why for inquisitively up will beautifully should.',
    studio: 'Thunderkick',
    rating: 2.5800171307883573,
    thumbnail: 'https://placehold.co/300x200?text=High-Level+Body',
    type: 'baccarat',
    categories: ['megaways', 'new'],
    rtp: 96.94811786606336,
    volatility: 'medium',
    release_date: '2018-02-11T01:09:31.53094816Z',
    features: ['respins'],
    has_jackpot: true,
    demo_url: 'https://demo.casino.com/game/high-level-body-20',
    provider_game_id: 'high-level-body-20',
    supported_platforms: ['mobile', 'tablet'],
  },
];
